services:
  postgres:
    image: postgres:16
    container_name: lab-postgres_db
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lab-network

  evolution-api:
    container_name: lab-evolution-api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - lab_evolution_instances:/lab_evolution/instances
    env_file:
      - .env
    networks:
      - lab-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: lab-ngrok
    restart: always
    ports:
      - 4040:4040
    env_file:
      - .env
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: start --all --config /etc/ngrok.yml
    depends_on:
      - n8n
      - evolution-api
    networks:
      - lab-network

  redis:
    image: bitnami/redis:latest
    container_name: lab-redis
    restart: always
    env_file:
      - .env
    ports:
      - 6380:6379
    networks:
      - lab-network
    volumes:
      - 'redis_data:/bitnami/redis/data'

  adminer:
    image: adminer
    container_name: lab-adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - lab-network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: lab-n8n
    restart: always
    ports:
      - 5678:5678
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - lab-network

volumes:
  n8n_data:
  postgres_data:
  lab_evolution_instances:
  redis_data:
    driver: local

networks:
  lab-network:
    driver: bridge